version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/1

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379/1

volumes:
  postgres_data: